#%RAML 1.0 DataType
type: array
items:   
  properties:
    firstName:
      type: string
      required: true
    lastName:
      type: string
      required: true
    DOB:
      type: date-only
      required: true
    email:
      type: string
      required: true
    employmentType:
      type: string
      required: true
    yearsOfExperience:
      type: string
      required: true
    package:
      type: string
      required: true
    previousCompany:
      type: string
      required: true
    careerStartDate:
      type: date-only
      required: true
    businessDomain:
      type: string
    BGVStatus:
      type: string
    projectPool:
      type: string
    HREmail:
      type: string
    DOJ:
      type: date-only

