[
  {
    "firstName": "John",
    "lastName": "Smith",
    "DOB": "1988-07-22",
    "email": "john.smith@example.com",
    "employmentType": "INTERN",
    "DOJ": "2021-01-15"
  },
  {
    "firstName": "Jane",
    "lastName": "Doe",
    "DOB": "1990-04-18",
    "email": "jane.doe@example.com",
    "employmentType": "INTERN",
    "DOJ": "2022-03-01"
  },
  {
    "firstName": "Alice",
    "lastName": "Johnson",
    "DOB": "1995-09-30",
    "email": "alice.johnson@example.com",
    "employmentType": "INTERN",
    "DOJ": "2023-02-20"
  },
  {
    "firstName": "Bob",
    "lastName": "Brown",
    "DOB": "1993-05-12",
    "email": "bob.brown@example.com",
    "employmentType": "INTERN",
    "DOJ": "2021-07-10"
  },
  {
    "firstName": "Charlie",
    "lastName": "Davis",
    "DOB": "1991-11-25",
    "email": "charlie.davis@example.com",
    "employmentType": "INTERN",
    "DOJ": "2020-06-15"
  }
]
